---
- name: Create public networks
  os_network:
    state: present
    name: "{{ item.net_name }}"
    external: false
  with_items: "{{ public_subnets }}"

- name: Create public subnets
  os_subnet:
    state: present
    network_name: "{{ item.net_name }}"
    name: "{{ item.subnet_name }}"
    cidr: "{{ item.cidr }}"
    dns_nameservers: "{{ dns_servers }}"
    host_routes:
      - destination: 0.0.0.0/0
        nexthop: "{{ item.internet_router_gateway_ip }}"
    allocation_pool_start: "{{ item.allocation_pool_start }}"
    allocation_pool_end: "{{ item.allocation_pool_end }}"
  with_items: "{{ public_subnets }}"
    
# No mans net is so the two routers can communicate to each other.
# Ultimately there will be a route on the internal router that will
# route internet traffic comming from VMs attached to the private subnets
# to the internet router. No VMS should be attached to this network. Ever.
- name: Create no-mans-net
  os_network:
    state: present
    name: "{{ no_mans_net.net_name }}"
    external: false

- name: Create no_mans_subnet
  os_subnet:
    state: present
    network_name: "{{ no_mans_net.net_name }}"
    name: "{{ no_mans_net.subnet_name }}"
    cidr: "{{ no_mans_net.cidr }}"
    enable_dhcp: false
    
- name: Create private networks
  os_network:
    state: present
    name: "{{ item.net_name }}"
    external: false
  with_items: "{{ private_subnets }}"

- name: Create private subnets
  os_subnet:
    state: present
    network_name: "{{ item.net_name }}"
    name: "{{ item.subnet_name }}"
    cidr: "{{ item.cidr }}"
    dns_nameservers: "{{ dns_servers }}"
    gateway_ip: "{{ item.internal_router_gateway_ip }}"
  with_items: "{{ private_subnets }}"
