---
# Blah Blah copyright
# blah blah no warranty
# blah blah apache license

- name: Create the ext-net provider network
  quantum_network:
    login_username: "admin"
    login_password: "ccaba142f6c98315476f2db4be0571edd6"
    login_tenant_name: "admin"
    auth_url: "http://172.29.236.200:5000/v2.0/"
    name: "ext-net"
    tenant_name: "admin"
    state: "present"
    provider_network_type: "flat"
    provider_physical_network: "flat"
    router_external: "yes"
    shared: "true"
    
