---
- name: Create public networks
  os_network:
    state: present
    name: "{{ item.net_name }}"
    external: true
  with_items: "{{ public_subnets }}"

- name: Create public subnets
  os_subnet:
    state: present
    network_name: "{{ item.net_name }}"
    name: "{{ item.subnet_name }}"
    cidr: "{{ item.cidr }}"
    dns_nameservers: "{{ dns_servers }}"
    host_routes:
      - destination: 0.0.0.0/0
        nexthop: "{{ item.internet_router_gateway_ip }}"
      - destination: 10.0.0.0/8
        nexthop: "{{ item.internal_router_gateway_ip }}"
    allocation_pool_start: "{{ item.allocation_pool_start }}"
    allocation_pool_end: "{{ item.allocation_pool_end }}"
  with_items: "{{ public_subnets }}"
    
    
    
