---
#- name: Set fact for interfaces
#  set_fact: interfaces_fact={{ item.subnet_name }}
#  with_items: "{{ public_subnets }}"
#  register: interfaces_result
#
#
#- name: Make interfaces list
#  set_fact: interfaces={{ interfaces_result.results | map(attribute='ansible_facts.interfaces_fact') | list }}
  
#- name: Debug interfaces list
#  debug: var=interfaces

- name: Delete Internet Router
  os_router:
    name: internet_router
    state: absent
    #network: "{{ external_network_name }}"
   # external_fixed_ips: "{{ internet_router_external_fixed_ips }}"
    #interfaces: "{{ interfaces }}"
- name: Delete Internal Router
  os_router:
    name: internal_router
    state: absent
